import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!supabaseUrl || !supabaseKey) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey, {
  auth: { autoRefreshToken: false, persistSession: false },
});

function basePrice(iplPrice: number): number {
  if (iplPrice > 10) return 2;
  if (iplPrice > 5) return 1;
  if (iplPrice > 2) return 0.5;
  return 0.2;
}

interface PlayerSeed {
  name: string;
  team: string;
  role: 'Batter' | 'Bowler' | 'All-Rounder' | 'Wicketkeeper';
  nationality: 'Indian' | 'Overseas';
  country: string;
  batting_style: string;
  bowling_style: string;
  ipl_price: number;
  base_price: number;
  rating: number;
  photo_url: string | null;
  career_stats: {
    matches: number;
    runs: number;
    wickets: number;
    batting_avg: number;
    batting_sr: number;
    bowling_avg: number;
    economy: number;
    highest_score: number;
    best_bowling: string;
    fifties: number;
    hundreds: number;
  };
  season: string;
}

function p(
  name: string,
  team: string,
  role: PlayerSeed['role'],
  nationality: PlayerSeed['nationality'],
  country: string,
  batting_style: string,
  bowling_style: string,
  ipl_price: number,
  rating: number,
  career_stats: PlayerSeed['career_stats'],
  photo_url: string | null = null
): PlayerSeed {
  return {
    name,
    team,
    role,
    nationality,
    country,
    batting_style,
    bowling_style,
    ipl_price,
    base_price: basePrice(ipl_price),
    rating,
    photo_url,
    career_stats,
    season: 'IPL 2026',
  };
}

const players: PlayerSeed[] = [
  // ============================================================
  // CSK - Chennai Super Kings (25 players)
  // ============================================================
  p('Ruturaj Gaikwad', 'CSK', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 18, 90,
    { matches: 120, runs: 3780, wickets: 1, batting_avg: 38.57, batting_sr: 138.46, bowling_avg: 62.00, economy: 9.30, highest_score: 108, best_bowling: '1/18', fifties: 28, hundreds: 2 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316614.png'),
  p('MS Dhoni', 'CSK', 'Wicketkeeper', 'Indian', 'India', 'Right-hand bat', 'Right-arm medium', 4, 85,
    { matches: 272, runs: 5320, wickets: 0, batting_avg: 38.09, batting_sr: 136.75, bowling_avg: 0, economy: 0, highest_score: 84, best_bowling: '0/0', fifties: 24, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316601.png'),
  p('Sanju Samson', 'CSK', 'Wicketkeeper', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 14, 88,
    { matches: 178, runs: 4580, wickets: 0, batting_avg: 29.87, batting_sr: 137.65, bowling_avg: 0, economy: 0, highest_score: 119, best_bowling: '0/0', fifties: 24, hundreds: 3 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316618.png'),
  p('Shivam Dube', 'CSK', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Right-arm medium-fast', 12, 79,
    { matches: 108, runs: 2010, wickets: 27, batting_avg: 30.45, batting_sr: 149.33, bowling_avg: 44.80, economy: 9.58, highest_score: 95, best_bowling: '2/12', fifties: 9, hundreds: 0 },
    null),
  p('Ayush Mhatre', 'CSK', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 4, 72,
    { matches: 12, runs: 280, wickets: 0, batting_avg: 25.45, batting_sr: 142.86, bowling_avg: 0, economy: 0, highest_score: 68, best_bowling: '0/0', fifties: 2, hundreds: 0 },
    null),
  p('Dewald Brevis', 'CSK', 'All-Rounder', 'Overseas', 'South Africa', 'Right-hand bat', 'Right-arm leg-break', 3.6, 75,
    { matches: 32, runs: 620, wickets: 8, batting_avg: 22.14, batting_sr: 155.00, bowling_avg: 36.50, economy: 8.90, highest_score: 49, best_bowling: '2/25', fifties: 0, hundreds: 0 },
    null),
  p('Urvil Patel', 'CSK', 'Wicketkeeper', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 1.2, 65,
    { matches: 8, runs: 145, wickets: 0, batting_avg: 20.71, batting_sr: 168.60, bowling_avg: 0, economy: 0, highest_score: 52, best_bowling: '0/0', fifties: 1, hundreds: 0 },
    null),
  p('Jamie Overton', 'CSK', 'All-Rounder', 'Overseas', 'England', 'Right-hand bat', 'Right-arm fast-medium', 1.5, 70,
    { matches: 25, runs: 310, wickets: 22, batting_avg: 19.37, batting_sr: 145.79, bowling_avg: 30.68, economy: 8.95, highest_score: 46, best_bowling: '3/28', fifties: 0, hundreds: 0 },
    null),
  p('Ramakrishna Ghosh', 'CSK', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm medium', 0.3, 60,
    { matches: 3, runs: 28, wickets: 1, batting_avg: 14.00, batting_sr: 121.74, bowling_avg: 42.00, economy: 9.50, highest_score: 18, best_bowling: '1/22', fifties: 0, hundreds: 0 },
    null),
  p('Noor Ahmad', 'CSK', 'Bowler', 'Overseas', 'Afghanistan', 'Right-hand bat', 'Slow left-arm chinaman', 10, 78,
    { matches: 42, runs: 30, wickets: 55, batting_avg: 5.00, batting_sr: 71.43, bowling_avg: 21.45, economy: 7.72, highest_score: 10, best_bowling: '4/19', fifties: 0, hundreds: 0 },
    null),
  p('Khaleel Ahmed', 'CSK', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Left-arm fast-medium', 5.25, 76,
    { matches: 80, runs: 52, wickets: 88, batting_avg: 4.33, batting_sr: 74.29, bowling_avg: 28.40, economy: 9.05, highest_score: 13, best_bowling: '4/36', fifties: 0, hundreds: 0 },
    null),
  p('Anshul Kamboj', 'CSK', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 3.4, 68,
    { matches: 18, runs: 35, wickets: 20, batting_avg: 5.83, batting_sr: 87.50, bowling_avg: 27.50, economy: 8.85, highest_score: 12, best_bowling: '3/22', fifties: 0, hundreds: 0 },
    null),
  p('Gurjapneet Singh', 'CSK', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Left-arm fast-medium', 0.3, 62,
    { matches: 5, runs: 4, wickets: 5, batting_avg: 2.00, batting_sr: 57.14, bowling_avg: 28.00, economy: 8.75, highest_score: 3, best_bowling: '2/18', fifties: 0, hundreds: 0 },
    null),
  p('Shreyas Gopal', 'CSK', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 1.1, 66,
    { matches: 62, runs: 245, wickets: 48, batting_avg: 12.25, batting_sr: 118.84, bowling_avg: 30.21, economy: 8.34, highest_score: 39, best_bowling: '3/12', fifties: 0, hundreds: 0 },
    null),
  p('Mukesh Choudhary', 'CSK', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Left-arm fast-medium', 0.7, 64,
    { matches: 22, runs: 12, wickets: 18, batting_avg: 3.00, batting_sr: 60.00, bowling_avg: 32.78, economy: 9.48, highest_score: 6, best_bowling: '3/25', fifties: 0, hundreds: 0 },
    null),
  p('Nathan Ellis', 'CSK', 'Bowler', 'Overseas', 'Australia', 'Right-hand bat', 'Right-arm fast-medium', 1.5, 71,
    { matches: 28, runs: 22, wickets: 30, batting_avg: 4.40, batting_sr: 78.57, bowling_avg: 26.93, economy: 8.52, highest_score: 8, best_bowling: '4/20', fifties: 0, hundreds: 0 },
    null),
  p('Akeal Hosein', 'CSK', 'All-Rounder', 'Overseas', 'West Indies', 'Left-hand bat', 'Slow left-arm orthodox', 2, 73,
    { matches: 35, runs: 180, wickets: 32, batting_avg: 12.00, batting_sr: 112.50, bowling_avg: 28.75, economy: 7.25, highest_score: 34, best_bowling: '3/18', fifties: 0, hundreds: 0 },
    null),
  p('Prashant Veer', 'CSK', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Slow left-arm orthodox', 14.2, 70,
    { matches: 5, runs: 42, wickets: 4, batting_avg: 14.00, batting_sr: 127.27, bowling_avg: 34.50, economy: 8.10, highest_score: 22, best_bowling: '2/20', fifties: 0, hundreds: 0 },
    null),
  p('Kartik Sharma', 'CSK', 'Wicketkeeper', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 14.2, 68,
    { matches: 4, runs: 55, wickets: 0, batting_avg: 18.33, batting_sr: 130.95, bowling_avg: 0, economy: 0, highest_score: 28, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Matthew Short', 'CSK', 'All-Rounder', 'Overseas', 'Australia', 'Right-hand bat', 'Right-arm off-break', 1.5, 72,
    { matches: 20, runs: 380, wickets: 5, batting_avg: 23.75, batting_sr: 148.44, bowling_avg: 38.20, economy: 8.45, highest_score: 62, best_bowling: '1/14', fifties: 2, hundreds: 0 },
    null),
  p('Aman Khan', 'CSK', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm medium', 0.4, 60,
    { matches: 4, runs: 32, wickets: 1, batting_avg: 10.67, batting_sr: 128.00, bowling_avg: 48.00, economy: 10.00, highest_score: 18, best_bowling: '1/24', fifties: 0, hundreds: 0 },
    null),
  p('Sarfaraz Khan', 'CSK', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 0.75, 74,
    { matches: 32, runs: 650, wickets: 0, batting_avg: 32.50, batting_sr: 142.86, bowling_avg: 0, economy: 0, highest_score: 71, best_bowling: '0/0', fifties: 5, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316636.png'),
  p('Matt Henry', 'CSK', 'Bowler', 'Overseas', 'New Zealand', 'Right-hand bat', 'Right-arm fast-medium', 2, 75,
    { matches: 30, runs: 42, wickets: 38, batting_avg: 6.00, batting_sr: 82.35, bowling_avg: 24.68, economy: 7.85, highest_score: 12, best_bowling: '4/22', fifties: 0, hundreds: 0 },
    null),
  p('Rahul Chahar', 'CSK', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 5.2, 76,
    { matches: 82, runs: 48, wickets: 78, batting_avg: 4.80, batting_sr: 80.00, bowling_avg: 27.33, economy: 8.12, highest_score: 12, best_bowling: '4/17', fifties: 0, hundreds: 0 },
    null),
  p('Zak Foulkes', 'CSK', 'All-Rounder', 'Overseas', 'Australia', 'Right-hand bat', 'Right-arm fast-medium', 0.75, 62,
    { matches: 6, runs: 18, wickets: 5, batting_avg: 6.00, batting_sr: 100.00, bowling_avg: 32.60, economy: 9.20, highest_score: 8, best_bowling: '2/28', fifties: 0, hundreds: 0 },
    null),

  // ============================================================
  // MI - Mumbai Indians (25 players)
  // ============================================================
  p('Hardik Pandya', 'MI', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 16.35, 88,
    { matches: 152, runs: 2650, wickets: 68, batting_avg: 28.80, batting_sr: 149.72, bowling_avg: 30.50, economy: 8.85, highest_score: 91, best_bowling: '3/17', fifties: 10, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316607.png'),
  p('Rohit Sharma', 'MI', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 16.3, 90,
    { matches: 260, runs: 6628, wickets: 15, batting_avg: 29.97, batting_sr: 131.17, bowling_avg: 46.20, economy: 8.68, highest_score: 109, best_bowling: '1/7', fifties: 44, hundreds: 2 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316603.png'),
  p('Suryakumar Yadav', 'MI', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm medium', 16.35, 93,
    { matches: 165, runs: 4420, wickets: 0, batting_avg: 32.50, batting_sr: 147.33, bowling_avg: 0, economy: 0, highest_score: 117, best_bowling: '0/0', fifties: 30, hundreds: 1 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316602.png'),
  p('Jasprit Bumrah', 'MI', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast', 18, 97,
    { matches: 142, runs: 56, wickets: 175, batting_avg: 5.60, batting_sr: 66.67, bowling_avg: 20.46, economy: 6.56, highest_score: 16, best_bowling: '5/10', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316604.png'),
  p('Tilak Varma', 'MI', 'Batter', 'Indian', 'India', 'Left-hand bat', 'Right-arm off-break', 8, 82,
    { matches: 58, runs: 1520, wickets: 2, batting_avg: 33.04, batting_sr: 142.29, bowling_avg: 52.00, economy: 9.20, highest_score: 84, best_bowling: '1/16', fifties: 10, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316621.png'),
  p('Ryan Rickelton', 'MI', 'Wicketkeeper', 'Overseas', 'South Africa', 'Left-hand bat', 'Right-arm off-break', 1, 70,
    { matches: 15, runs: 320, wickets: 0, batting_avg: 26.67, batting_sr: 135.59, bowling_avg: 0, economy: 0, highest_score: 62, best_bowling: '0/0', fifties: 2, hundreds: 0 },
    null),
  p('Robin Minz', 'MI', 'Wicketkeeper', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.65, 62,
    { matches: 5, runs: 68, wickets: 0, batting_avg: 17.00, batting_sr: 141.67, bowling_avg: 0, economy: 0, highest_score: 32, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Raj Angad Bawa', 'MI', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Right-arm fast-medium', 2, 65,
    { matches: 10, runs: 82, wickets: 5, batting_avg: 13.67, batting_sr: 118.84, bowling_avg: 38.80, economy: 9.40, highest_score: 28, best_bowling: '2/22', fifties: 0, hundreds: 0 },
    null),
  p('Raghu Sharma', 'MI', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 0.3, 58,
    { matches: 2, runs: 4, wickets: 2, batting_avg: 4.00, batting_sr: 66.67, bowling_avg: 28.50, economy: 8.50, highest_score: 3, best_bowling: '1/14', fifties: 0, hundreds: 0 },
    null),
  p('Mitchell Santner', 'MI', 'All-Rounder', 'Overseas', 'New Zealand', 'Left-hand bat', 'Slow left-arm orthodox', 2, 74,
    { matches: 55, runs: 410, wickets: 48, batting_avg: 16.40, batting_sr: 117.14, bowling_avg: 29.63, economy: 7.08, highest_score: 45, best_bowling: '4/11', fifties: 0, hundreds: 0 },
    null),
  p('Corbin Bosch', 'MI', 'All-Rounder', 'Overseas', 'South Africa', 'Right-hand bat', 'Right-arm fast-medium', 1.1, 68,
    { matches: 10, runs: 85, wickets: 10, batting_avg: 14.17, batting_sr: 130.77, bowling_avg: 28.90, economy: 8.72, highest_score: 25, best_bowling: '2/18', fifties: 0, hundreds: 0 },
    null),
  p('Naman Dhir', 'MI', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Right-arm off-break', 5.25, 70,
    { matches: 8, runs: 145, wickets: 2, batting_avg: 24.17, batting_sr: 148.97, bowling_avg: 40.50, economy: 8.80, highest_score: 48, best_bowling: '1/18', fifties: 0, hundreds: 0 },
    null),
  p('Trent Boult', 'MI', 'Bowler', 'Overseas', 'New Zealand', 'Right-hand bat', 'Left-arm fast', 12.5, 87,
    { matches: 105, runs: 118, wickets: 125, batting_avg: 6.56, batting_sr: 95.16, bowling_avg: 24.88, economy: 8.18, highest_score: 16, best_bowling: '4/18', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304630.png'),
  p('Allah Ghazanfar', 'MI', 'Bowler', 'Overseas', 'Afghanistan', 'Right-hand bat', 'Right-arm off-break', 4.8, 72,
    { matches: 12, runs: 15, wickets: 14, batting_avg: 3.75, batting_sr: 62.50, bowling_avg: 23.57, economy: 7.45, highest_score: 6, best_bowling: '3/21', fifties: 0, hundreds: 0 },
    null),
  p('Ashwani Kumar', 'MI', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 0.3, 58,
    { matches: 2, runs: 3, wickets: 1, batting_avg: 3.00, batting_sr: 50.00, bowling_avg: 38.00, economy: 9.50, highest_score: 3, best_bowling: '1/19', fifties: 0, hundreds: 0 },
    null),
  p('Deepak Chahar', 'MI', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 9.25, 78,
    { matches: 120, runs: 365, wickets: 115, batting_avg: 14.04, batting_sr: 113.35, bowling_avg: 27.05, economy: 7.62, highest_score: 42, best_bowling: '6/7', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304646.png'),
  p('Will Jacks', 'MI', 'All-Rounder', 'Overseas', 'England', 'Right-hand bat', 'Right-arm off-break', 5.25, 80,
    { matches: 28, runs: 620, wickets: 12, batting_avg: 28.18, batting_sr: 162.30, bowling_avg: 32.50, economy: 8.45, highest_score: 82, best_bowling: '2/15', fifties: 4, hundreds: 0 },
    null),
  p('Sherfane Rutherford', 'MI', 'All-Rounder', 'Overseas', 'West Indies', 'Left-hand bat', 'Right-arm medium', 2.6, 72,
    { matches: 30, runs: 420, wickets: 2, batting_avg: 21.00, batting_sr: 153.28, bowling_avg: 48.00, economy: 10.20, highest_score: 68, best_bowling: '1/22', fifties: 2, hundreds: 0 },
    null),
  p('Mayank Markande', 'MI', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 0.3, 60,
    { matches: 18, runs: 10, wickets: 15, batting_avg: 3.33, batting_sr: 55.56, bowling_avg: 30.80, economy: 8.55, highest_score: 5, best_bowling: '3/22', fifties: 0, hundreds: 0 },
    null),
  p('Shardul Thakur', 'MI', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 4.2, 75,
    { matches: 112, runs: 560, wickets: 98, batting_avg: 14.74, batting_sr: 138.61, bowling_avg: 30.77, economy: 9.10, highest_score: 68, best_bowling: '4/27', fifties: 1, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304647.png'),
  p('Quinton de Kock', 'MI', 'Wicketkeeper', 'Overseas', 'South Africa', 'Left-hand bat', 'Right-arm off-break', 1, 82,
    { matches: 100, runs: 2780, wickets: 0, batting_avg: 31.59, batting_sr: 139.00, bowling_avg: 0, economy: 0, highest_score: 104, best_bowling: '0/0', fifties: 18, hundreds: 2 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304633.png'),
  p('Danish Malewar', 'MI', 'Batter', 'Indian', 'India', 'Left-hand bat', 'Right-arm off-break', 0.3, 58,
    { matches: 3, runs: 35, wickets: 0, batting_avg: 11.67, batting_sr: 134.62, bowling_avg: 0, economy: 0, highest_score: 22, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Mohammad Izhar', 'MI', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Mayank Rawat', 'MI', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Atharva Ankolekar', 'MI', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 0.3, 60,
    { matches: 6, runs: 35, wickets: 5, batting_avg: 8.75, batting_sr: 109.38, bowling_avg: 32.40, economy: 8.10, highest_score: 15, best_bowling: '2/18', fifties: 0, hundreds: 0 },
    null),

  // ============================================================
  // RCB - Royal Challengers Bengaluru (25 players)
  // ============================================================
  p('Rajat Patidar', 'RCB', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 11, 83,
    { matches: 42, runs: 1180, wickets: 0, batting_avg: 33.71, batting_sr: 155.26, bowling_avg: 0, economy: 0, highest_score: 112, best_bowling: '0/0', fifties: 6, hundreds: 1 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316625.png'),
  p('Virat Kohli', 'RCB', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm medium', 21, 95,
    { matches: 262, runs: 8004, wickets: 4, batting_avg: 37.39, batting_sr: 131.97, bowling_avg: 62.00, economy: 8.80, highest_score: 113, best_bowling: '1/5', fifties: 55, hundreds: 8 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316605.png'),
  p('Devdutt Padikkal', 'RCB', 'Batter', 'Indian', 'India', 'Left-hand bat', 'Right-arm off-break', 2, 72,
    { matches: 62, runs: 1470, wickets: 0, batting_avg: 26.25, batting_sr: 127.83, bowling_avg: 0, economy: 0, highest_score: 101, best_bowling: '0/0', fifties: 9, hundreds: 1 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316634.png'),
  p('Phil Salt', 'RCB', 'Wicketkeeper', 'Overseas', 'England', 'Right-hand bat', 'Right-arm off-break', 11.5, 86,
    { matches: 38, runs: 1120, wickets: 0, batting_avg: 32.94, batting_sr: 168.42, bowling_avg: 0, economy: 0, highest_score: 89, best_bowling: '0/0', fifties: 8, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316624.png'),
  p('Jitesh Sharma', 'RCB', 'Wicketkeeper', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 11, 76,
    { matches: 42, runs: 720, wickets: 0, batting_avg: 22.50, batting_sr: 158.59, bowling_avg: 0, economy: 0, highest_score: 49, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Krunal Pandya', 'RCB', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 5.75, 75,
    { matches: 120, runs: 1580, wickets: 65, batting_avg: 22.57, batting_sr: 136.21, bowling_avg: 31.23, economy: 7.48, highest_score: 86, best_bowling: '4/20', fifties: 4, hundreds: 0 },
    null),
  p('Swapnil Singh', 'RCB', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 0.5, 60,
    { matches: 10, runs: 48, wickets: 8, batting_avg: 9.60, batting_sr: 120.00, bowling_avg: 30.50, economy: 7.85, highest_score: 18, best_bowling: '2/16', fifties: 0, hundreds: 0 },
    null),
  p('Tim David', 'RCB', 'All-Rounder', 'Overseas', 'Singapore', 'Right-hand bat', 'Right-arm off-break', 3, 77,
    { matches: 48, runs: 980, wickets: 0, batting_avg: 26.49, batting_sr: 169.83, bowling_avg: 0, economy: 0, highest_score: 72, best_bowling: '0/0', fifties: 3, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316632.png'),
  p('Romario Shepherd', 'RCB', 'All-Rounder', 'Overseas', 'West Indies', 'Right-hand bat', 'Right-arm fast-medium', 1.5, 70,
    { matches: 18, runs: 165, wickets: 14, batting_avg: 16.50, batting_sr: 137.50, bowling_avg: 32.14, economy: 9.35, highest_score: 36, best_bowling: '2/18', fifties: 0, hundreds: 0 },
    null),
  p('Jacob Bethell', 'RCB', 'All-Rounder', 'Overseas', 'England', 'Left-hand bat', 'Slow left-arm orthodox', 2.6, 74,
    { matches: 12, runs: 240, wickets: 4, batting_avg: 24.00, batting_sr: 150.00, bowling_avg: 36.00, economy: 8.20, highest_score: 55, best_bowling: '1/12', fifties: 1, hundreds: 0 },
    null),
  p('Josh Hazlewood', 'RCB', 'Bowler', 'Overseas', 'Australia', 'Left-hand bat', 'Right-arm fast', 12.5, 88,
    { matches: 52, runs: 28, wickets: 62, batting_avg: 4.67, batting_sr: 63.64, bowling_avg: 23.90, economy: 7.68, highest_score: 9, best_bowling: '5/18', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304636.png'),
  p('Yash Dayal', 'RCB', 'Bowler', 'Indian', 'India', 'Left-hand bat', 'Left-arm fast-medium', 5, 74,
    { matches: 30, runs: 22, wickets: 30, batting_avg: 3.67, batting_sr: 68.75, bowling_avg: 29.67, economy: 9.22, highest_score: 8, best_bowling: '3/18', fifties: 0, hundreds: 0 },
    null),
  p('Bhuvneshwar Kumar', 'RCB', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 10.75, 80,
    { matches: 176, runs: 310, wickets: 185, batting_avg: 8.86, batting_sr: 96.88, bowling_avg: 25.28, economy: 7.20, highest_score: 24, best_bowling: '5/19', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304645.png'),
  p('Nuwan Thushara', 'RCB', 'Bowler', 'Overseas', 'Sri Lanka', 'Right-hand bat', 'Right-arm fast', 1.6, 72,
    { matches: 18, runs: 8, wickets: 18, batting_avg: 2.67, batting_sr: 53.33, bowling_avg: 26.83, economy: 8.92, highest_score: 5, best_bowling: '3/15', fifties: 0, hundreds: 0 },
    null),
  p('Rasikh Dar', 'RCB', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast', 6, 73,
    { matches: 22, runs: 12, wickets: 22, batting_avg: 3.00, batting_sr: 60.00, bowling_avg: 28.45, economy: 9.15, highest_score: 6, best_bowling: '3/20', fifties: 0, hundreds: 0 },
    null),
  p('Abhinandan Singh', 'RCB', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Suyash Sharma', 'RCB', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 2.6, 68,
    { matches: 12, runs: 8, wickets: 10, batting_avg: 2.67, batting_sr: 50.00, bowling_avg: 30.20, economy: 8.40, highest_score: 4, best_bowling: '2/18', fifties: 0, hundreds: 0 },
    null),
  p('Venkatesh Iyer', 'RCB', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Right-arm medium', 7, 78,
    { matches: 52, runs: 1250, wickets: 10, batting_avg: 28.41, batting_sr: 138.89, bowling_avg: 42.00, economy: 9.20, highest_score: 104, best_bowling: '2/20', fifties: 6, hundreds: 1 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316626.png'),
  p('Jacob Duffy', 'RCB', 'Bowler', 'Overseas', 'New Zealand', 'Right-hand bat', 'Right-arm fast-medium', 0.75, 65,
    { matches: 8, runs: 10, wickets: 8, batting_avg: 3.33, batting_sr: 58.82, bowling_avg: 28.75, economy: 8.50, highest_score: 5, best_bowling: '2/22', fifties: 0, hundreds: 0 },
    null),
  p('Satvik Deswal', 'RCB', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Mangesh Yadav', 'RCB', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Vihaan Malhotra', 'RCB', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Kanishk Chouhan', 'RCB', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Slow left-arm orthodox', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Vicky Ostwal', 'RCB', 'Bowler', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 0.3, 58,
    { matches: 4, runs: 5, wickets: 3, batting_avg: 2.50, batting_sr: 55.56, bowling_avg: 32.00, economy: 8.00, highest_score: 3, best_bowling: '2/20', fifties: 0, hundreds: 0 },
    null),
  p('Jordan Cox', 'RCB', 'Wicketkeeper', 'Overseas', 'England', 'Right-hand bat', 'Right-arm off-break', 0.75, 65,
    { matches: 8, runs: 140, wickets: 0, batting_avg: 20.00, batting_sr: 130.84, bowling_avg: 0, economy: 0, highest_score: 38, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),

  // ============================================================
  // KKR - Kolkata Knight Riders (25 players)
  // ============================================================
  p('Ajinkya Rahane', 'KKR', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 4, 76,
    { matches: 178, runs: 4350, wickets: 0, batting_avg: 28.43, batting_sr: 122.19, bowling_avg: 0, economy: 0, highest_score: 105, best_bowling: '0/0', fifties: 24, hundreds: 2 },
    null),
  p('Rinku Singh', 'KKR', 'Batter', 'Indian', 'India', 'Left-hand bat', 'Right-arm off-break', 13, 84,
    { matches: 52, runs: 1210, wickets: 0, batting_avg: 33.61, batting_sr: 155.97, bowling_avg: 0, economy: 0, highest_score: 82, best_bowling: '0/0', fifties: 7, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316622.png'),
  p('Sunil Narine', 'KKR', 'All-Rounder', 'Overseas', 'West Indies', 'Left-hand bat', 'Right-arm off-break', 12, 85,
    { matches: 190, runs: 2280, wickets: 172, batting_avg: 18.55, batting_sr: 166.30, bowling_avg: 26.55, economy: 6.65, highest_score: 109, best_bowling: '5/19', fifties: 6, hundreds: 1 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304635.png'),
  p('Varun Chakravarthy', 'KKR', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 12, 84,
    { matches: 60, runs: 28, wickets: 72, batting_avg: 4.67, batting_sr: 70.00, bowling_avg: 22.22, economy: 7.32, highest_score: 8, best_bowling: '5/17', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316629.png'),
  p('Harshit Rana', 'KKR', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast', 11.75, 78,
    { matches: 22, runs: 28, wickets: 24, batting_avg: 5.60, batting_sr: 93.33, bowling_avg: 26.42, economy: 9.18, highest_score: 12, best_bowling: '3/24', fifties: 0, hundreds: 0 },
    null),
  p('Ramandeep Singh', 'KKR', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm medium', 4, 70,
    { matches: 28, runs: 320, wickets: 6, batting_avg: 18.82, batting_sr: 148.15, bowling_avg: 40.00, economy: 9.60, highest_score: 42, best_bowling: '1/8', fifties: 0, hundreds: 0 },
    null),
  p('Angkrish Raghuvanshi', 'KKR', 'Batter', 'Indian', 'India', 'Left-hand bat', 'Right-arm off-break', 3.2, 68,
    { matches: 8, runs: 140, wickets: 0, batting_avg: 20.00, batting_sr: 140.00, bowling_avg: 0, economy: 0, highest_score: 42, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Vaibhav Arora', 'KKR', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 1, 66,
    { matches: 14, runs: 8, wickets: 14, batting_avg: 2.67, batting_sr: 53.33, bowling_avg: 27.14, economy: 8.62, highest_score: 4, best_bowling: '3/16', fifties: 0, hundreds: 0 },
    null),
  p('Rovman Powell', 'KKR', 'Batter', 'Overseas', 'West Indies', 'Right-hand bat', 'Right-arm medium', 0.6, 72,
    { matches: 42, runs: 680, wickets: 2, batting_avg: 20.00, batting_sr: 155.48, bowling_avg: 52.00, economy: 10.40, highest_score: 68, best_bowling: '1/18', fifties: 3, hundreds: 0 },
    null),
  p('Manish Pandey', 'KKR', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.75, 68,
    { matches: 172, runs: 3942, wickets: 0, batting_avg: 29.41, batting_sr: 121.47, bowling_avg: 0, economy: 0, highest_score: 114, best_bowling: '0/0', fifties: 23, hundreds: 1 },
    null),
  p('Umran Malik', 'KKR', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast', 0.75, 70,
    { matches: 28, runs: 15, wickets: 22, batting_avg: 3.75, batting_sr: 57.69, bowling_avg: 30.91, economy: 10.08, highest_score: 6, best_bowling: '4/28', fifties: 0, hundreds: 0 },
    null),
  p('Anukul Roy', 'KKR', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 0.4, 62,
    { matches: 8, runs: 32, wickets: 5, batting_avg: 8.00, batting_sr: 106.67, bowling_avg: 32.60, economy: 7.80, highest_score: 14, best_bowling: '2/18', fifties: 0, hundreds: 0 },
    null),
  p('Cameron Green', 'KKR', 'All-Rounder', 'Overseas', 'Australia', 'Right-hand bat', 'Right-arm fast-medium', 25.2, 86,
    { matches: 22, runs: 480, wickets: 15, batting_avg: 26.67, batting_sr: 148.15, bowling_avg: 32.00, economy: 8.80, highest_score: 72, best_bowling: '2/14', fifties: 3, hundreds: 0 },
    null),
  p('Finn Allen', 'KKR', 'Wicketkeeper', 'Overseas', 'New Zealand', 'Right-hand bat', 'Right-arm off-break', 2, 74,
    { matches: 18, runs: 380, wickets: 0, batting_avg: 23.75, batting_sr: 172.73, bowling_avg: 0, economy: 0, highest_score: 66, best_bowling: '0/0', fifties: 2, hundreds: 0 },
    null),
  p('Matheesha Pathirana', 'KKR', 'Bowler', 'Overseas', 'Sri Lanka', 'Right-hand bat', 'Right-arm fast', 18, 87,
    { matches: 52, runs: 58, wickets: 74, batting_avg: 5.27, batting_sr: 90.63, bowling_avg: 19.78, economy: 8.55, highest_score: 18, best_bowling: '4/28', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/383400/383405.png'),
  p('Tejasvi Singh', 'KKR', 'Wicketkeeper', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 58,
    { matches: 2, runs: 18, wickets: 0, batting_avg: 9.00, batting_sr: 120.00, bowling_avg: 0, economy: 0, highest_score: 12, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Kartik Tyagi', 'KKR', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast', 0.3, 60,
    { matches: 12, runs: 8, wickets: 8, batting_avg: 2.67, batting_sr: 50.00, bowling_avg: 35.50, economy: 9.70, highest_score: 4, best_bowling: '2/24', fifties: 0, hundreds: 0 },
    null),
  p('Prashant Solanki', 'KKR', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 0.3, 58,
    { matches: 3, runs: 5, wickets: 2, batting_avg: 2.50, batting_sr: 55.56, bowling_avg: 36.00, economy: 9.00, highest_score: 3, best_bowling: '1/18', fifties: 0, hundreds: 0 },
    null),
  p('Rahul Tripathi', 'KKR', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 0.3, 72,
    { matches: 76, runs: 1822, wickets: 0, batting_avg: 27.60, batting_sr: 139.60, bowling_avg: 0, economy: 0, highest_score: 76, best_bowling: '0/0', fifties: 10, hundreds: 0 },
    null),
  p('Tim Seifert', 'KKR', 'Wicketkeeper', 'Overseas', 'New Zealand', 'Right-hand bat', 'Right-arm off-break', 1.5, 68,
    { matches: 15, runs: 225, wickets: 0, batting_avg: 18.75, batting_sr: 136.36, bowling_avg: 0, economy: 0, highest_score: 42, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Sarthak Ranjan', 'KKR', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm medium', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Daksh Kamra', 'KKR', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Rachin Ravindra', 'KKR', 'All-Rounder', 'Overseas', 'New Zealand', 'Left-hand bat', 'Slow left-arm orthodox', 2, 78,
    { matches: 22, runs: 480, wickets: 10, batting_avg: 26.67, batting_sr: 136.36, bowling_avg: 34.20, economy: 7.80, highest_score: 68, best_bowling: '2/22', fifties: 3, hundreds: 0 },
    null),
  p('Blessing Muzarabani', 'KKR', 'Bowler', 'Overseas', 'Zimbabwe', 'Right-hand bat', 'Right-arm fast', 0.5, 68,
    { matches: 10, runs: 8, wickets: 12, batting_avg: 2.67, batting_sr: 44.44, bowling_avg: 25.50, economy: 8.50, highest_score: 4, best_bowling: '3/22', fifties: 0, hundreds: 0 },
    null),
  p('Saurabh Dubey', 'KKR', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),

  // ============================================================
  // DC - Delhi Capitals (25 players)
  // ============================================================
  p('KL Rahul', 'DC', 'Wicketkeeper', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 14, 88,
    { matches: 132, runs: 4683, wickets: 0, batting_avg: 39.52, batting_sr: 134.62, bowling_avg: 0, economy: 0, highest_score: 132, best_bowling: '0/0', fifties: 37, hundreds: 4 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316609.png'),
  p('Karun Nair', 'DC', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 8, 80,
    { matches: 75, runs: 1420, wickets: 0, batting_avg: 24.48, batting_sr: 125.66, bowling_avg: 0, economy: 0, highest_score: 83, best_bowling: '0/0', fifties: 8, hundreds: 0 },
    null),
  p('Abishek Porel', 'DC', 'Wicketkeeper', 'Indian', 'India', 'Left-hand bat', 'Right-arm off-break', 3, 68,
    { matches: 14, runs: 230, wickets: 0, batting_avg: 19.17, batting_sr: 145.57, bowling_avg: 0, economy: 0, highest_score: 48, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Tristan Stubbs', 'DC', 'Wicketkeeper', 'Overseas', 'South Africa', 'Right-hand bat', 'Right-arm off-break', 10, 77,
    { matches: 25, runs: 520, wickets: 0, batting_avg: 24.76, batting_sr: 162.50, bowling_avg: 0, economy: 0, highest_score: 71, best_bowling: '0/0', fifties: 3, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/383400/383409.png'),
  p('Axar Patel', 'DC', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 16.5, 85,
    { matches: 120, runs: 1320, wickets: 92, batting_avg: 22.37, batting_sr: 140.43, bowling_avg: 28.37, economy: 7.25, highest_score: 64, best_bowling: '4/21', fifties: 3, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316623.png'),
  p('Sameer Rizvi', 'DC', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 6, 70,
    { matches: 8, runs: 110, wickets: 2, batting_avg: 15.71, batting_sr: 152.78, bowling_avg: 42.00, economy: 9.80, highest_score: 38, best_bowling: '1/18', fifties: 0, hundreds: 0 },
    null),
  p('Ashutosh Sharma', 'DC', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 3.8, 68,
    { matches: 12, runs: 210, wickets: 3, batting_avg: 21.00, batting_sr: 168.00, bowling_avg: 40.33, economy: 9.50, highest_score: 48, best_bowling: '1/14', fifties: 0, hundreds: 0 },
    null),
  p('Vipraj Nigam', 'DC', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 0.3, 58,
    { matches: 2, runs: 15, wickets: 1, batting_avg: 7.50, batting_sr: 107.14, bowling_avg: 38.00, economy: 8.80, highest_score: 10, best_bowling: '1/20', fifties: 0, hundreds: 0 },
    null),
  p('Ajay Mandal', 'DC', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm medium', 0.75, 62,
    { matches: 4, runs: 28, wickets: 2, batting_avg: 9.33, batting_sr: 121.74, bowling_avg: 35.00, economy: 9.10, highest_score: 15, best_bowling: '1/16', fifties: 0, hundreds: 0 },
    null),
  p('Tripurana Vijay', 'DC', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Madhav Tiwari', 'DC', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Mitchell Starc', 'DC', 'Bowler', 'Overseas', 'Australia', 'Left-hand bat', 'Left-arm fast', 11.75, 90,
    { matches: 48, runs: 62, wickets: 58, batting_avg: 6.89, batting_sr: 103.33, bowling_avg: 23.62, economy: 8.48, highest_score: 18, best_bowling: '6/16', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304627.png'),
  p('T Natarajan', 'DC', 'Bowler', 'Indian', 'India', 'Left-hand bat', 'Left-arm fast-medium', 3, 74,
    { matches: 40, runs: 18, wickets: 40, batting_avg: 3.60, batting_sr: 60.00, bowling_avg: 28.95, economy: 8.68, highest_score: 6, best_bowling: '4/23', fifties: 0, hundreds: 0 },
    null),
  p('Mukesh Kumar', 'DC', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 8, 75,
    { matches: 32, runs: 22, wickets: 30, batting_avg: 3.67, batting_sr: 61.11, bowling_avg: 30.33, economy: 9.22, highest_score: 8, best_bowling: '3/18', fifties: 0, hundreds: 0 },
    null),
  p('Dushmantha Chameera', 'DC', 'Bowler', 'Overseas', 'Sri Lanka', 'Right-hand bat', 'Right-arm fast', 1, 68,
    { matches: 15, runs: 10, wickets: 14, batting_avg: 2.50, batting_sr: 50.00, bowling_avg: 28.57, economy: 9.05, highest_score: 5, best_bowling: '3/20', fifties: 0, hundreds: 0 },
    null),
  p('Kuldeep Yadav', 'DC', 'Bowler', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm chinaman', 13.25, 86,
    { matches: 82, runs: 108, wickets: 88, batting_avg: 6.75, batting_sr: 90.00, bowling_avg: 23.82, economy: 7.95, highest_score: 20, best_bowling: '5/25', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316619.png'),
  p('Nitish Rana', 'DC', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Right-arm off-break', 3, 70,
    { matches: 108, runs: 2550, wickets: 10, batting_avg: 27.17, batting_sr: 135.11, bowling_avg: 38.80, economy: 8.72, highest_score: 87, best_bowling: '2/22', fifties: 14, hundreds: 0 },
    null),
  p('Auqib Dar', 'DC', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 8.4, 72,
    { matches: 5, runs: 62, wickets: 4, batting_avg: 15.50, batting_sr: 148.00, bowling_avg: 30.50, economy: 9.15, highest_score: 28, best_bowling: '2/22', fifties: 0, hundreds: 0 },
    null),
  p('Ben Duckett', 'DC', 'Batter', 'Overseas', 'England', 'Left-hand bat', 'Right-arm off-break', 1, 75,
    { matches: 12, runs: 280, wickets: 0, batting_avg: 28.00, batting_sr: 146.60, bowling_avg: 0, economy: 0, highest_score: 62, best_bowling: '0/0', fifties: 2, hundreds: 0 },
    null),
  p('David Miller', 'DC', 'Batter', 'Overseas', 'South Africa', 'Left-hand bat', 'Right-arm off-break', 2, 78,
    { matches: 122, runs: 2780, wickets: 0, batting_avg: 30.22, batting_sr: 140.91, bowling_avg: 0, economy: 0, highest_score: 101, best_bowling: '0/0', fifties: 14, hundreds: 1 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304631.png'),
  p('Pathum Nissanka', 'DC', 'Batter', 'Overseas', 'Sri Lanka', 'Right-hand bat', 'Right-arm off-break', 1, 76,
    { matches: 12, runs: 290, wickets: 0, batting_avg: 29.00, batting_sr: 142.16, bowling_avg: 0, economy: 0, highest_score: 65, best_bowling: '0/0', fifties: 2, hundreds: 0 },
    null),
  p('Lungi Ngidi', 'DC', 'Bowler', 'Overseas', 'South Africa', 'Right-hand bat', 'Right-arm fast', 1, 76,
    { matches: 28, runs: 20, wickets: 32, batting_avg: 4.00, batting_sr: 66.67, bowling_avg: 24.69, economy: 8.52, highest_score: 8, best_bowling: '4/18', fifties: 0, hundreds: 0 },
    null),
  p('Sahil Parakh', 'DC', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Prithvi Shaw', 'DC', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 65,
    { matches: 68, runs: 1650, wickets: 0, batting_avg: 26.61, batting_sr: 149.32, bowling_avg: 0, economy: 0, highest_score: 99, best_bowling: '0/0', fifties: 12, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316635.png'),
  p('Kyle Jamieson', 'DC', 'Bowler', 'Overseas', 'New Zealand', 'Right-hand bat', 'Right-arm fast-medium', 0.5, 72,
    { matches: 15, runs: 82, wickets: 15, batting_avg: 13.67, batting_sr: 120.59, bowling_avg: 30.27, economy: 9.12, highest_score: 22, best_bowling: '3/25', fifties: 0, hundreds: 0 },
    null),

  // ============================================================
  // LSG - Lucknow Super Giants (25 players)
  // ============================================================
  p('Rishabh Pant', 'LSG', 'Wicketkeeper', 'Indian', 'India', 'Left-hand bat', 'Right-arm off-break', 27, 92,
    { matches: 118, runs: 3680, wickets: 0, batting_avg: 34.39, batting_sr: 148.99, bowling_avg: 0, economy: 0, highest_score: 128, best_bowling: '0/0', fifties: 19, hundreds: 2 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316610.png'),
  p('Nicholas Pooran', 'LSG', 'Wicketkeeper', 'Overseas', 'West Indies', 'Left-hand bat', 'Right-arm off-break', 21, 85,
    { matches: 80, runs: 1920, wickets: 0, batting_avg: 28.66, batting_sr: 155.48, bowling_avg: 0, economy: 0, highest_score: 93, best_bowling: '0/0', fifties: 10, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304638.png'),
  p('Mayank Yadav', 'LSG', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast', 11, 80,
    { matches: 8, runs: 5, wickets: 10, batting_avg: 2.50, batting_sr: 62.50, bowling_avg: 18.80, economy: 7.35, highest_score: 3, best_bowling: '3/14', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/383400/383407.png'),
  p('Mohammed Shami', 'LSG', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast', 10, 84,
    { matches: 108, runs: 145, wickets: 118, batting_avg: 5.18, batting_sr: 82.39, bowling_avg: 26.53, economy: 8.28, highest_score: 18, best_bowling: '4/11', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304634.png'),
  p('Avesh Khan', 'LSG', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast', 9.75, 76,
    { matches: 62, runs: 42, wickets: 68, batting_avg: 4.67, batting_sr: 70.00, bowling_avg: 26.41, economy: 8.95, highest_score: 12, best_bowling: '4/18', fifties: 0, hundreds: 0 },
    null),
  p('Abdul Samad', 'LSG', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 2, 68,
    { matches: 45, runs: 520, wickets: 5, batting_avg: 17.33, batting_sr: 148.57, bowling_avg: 44.00, economy: 9.80, highest_score: 48, best_bowling: '1/10', fifties: 0, hundreds: 0 },
    null),
  p('Ayush Badoni', 'LSG', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 4, 72,
    { matches: 38, runs: 720, wickets: 6, batting_avg: 24.83, batting_sr: 145.45, bowling_avg: 38.67, economy: 9.20, highest_score: 54, best_bowling: '1/8', fifties: 3, hundreds: 0 },
    null),
  p('Mohsin Khan', 'LSG', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Left-arm fast-medium', 0.5, 66,
    { matches: 14, runs: 8, wickets: 16, batting_avg: 2.67, batting_sr: 53.33, bowling_avg: 22.50, economy: 7.55, highest_score: 4, best_bowling: '3/20', fifties: 0, hundreds: 0 },
    null),
  p('Mitchell Marsh', 'LSG', 'All-Rounder', 'Overseas', 'Australia', 'Right-hand bat', 'Right-arm fast-medium', 3.4, 80,
    { matches: 52, runs: 1120, wickets: 22, batting_avg: 28.00, batting_sr: 145.45, bowling_avg: 34.91, economy: 8.85, highest_score: 89, best_bowling: '2/18', fifties: 6, hundreds: 0 },
    null),
  p('Shahbaz Ahmed', 'LSG', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 1, 66,
    { matches: 48, runs: 510, wickets: 38, batting_avg: 19.62, batting_sr: 134.21, bowling_avg: 30.53, economy: 8.18, highest_score: 52, best_bowling: '3/21', fifties: 2, hundreds: 0 },
    null),
  p('Aiden Markram', 'LSG', 'Batter', 'Overseas', 'South Africa', 'Right-hand bat', 'Right-arm off-break', 2, 76,
    { matches: 32, runs: 680, wickets: 5, batting_avg: 25.19, batting_sr: 135.46, bowling_avg: 38.60, economy: 8.40, highest_score: 72, best_bowling: '1/12', fifties: 4, hundreds: 0 },
    null),
  p('Matthew Breetzke', 'LSG', 'Batter', 'Overseas', 'South Africa', 'Right-hand bat', 'Right-arm off-break', 0.75, 65,
    { matches: 5, runs: 85, wickets: 0, batting_avg: 17.00, batting_sr: 128.79, bowling_avg: 0, economy: 0, highest_score: 32, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Himmat Singh', 'LSG', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 58,
    { matches: 4, runs: 42, wickets: 0, batting_avg: 14.00, batting_sr: 127.27, bowling_avg: 0, economy: 0, highest_score: 22, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Arshin Kulkarni', 'LSG', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm medium', 0.3, 60,
    { matches: 3, runs: 35, wickets: 1, batting_avg: 11.67, batting_sr: 134.62, bowling_avg: 42.00, economy: 9.60, highest_score: 18, best_bowling: '1/22', fifties: 0, hundreds: 0 },
    null),
  p('Manimaran Siddharth', 'LSG', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Slow left-arm orthodox', 0.3, 62,
    { matches: 8, runs: 5, wickets: 8, batting_avg: 2.50, batting_sr: 50.00, bowling_avg: 26.50, economy: 7.35, highest_score: 3, best_bowling: '2/16', fifties: 0, hundreds: 0 },
    null),
  p('Digvesh Rathi', 'LSG', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Slow left-arm orthodox', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Prince Yadav', 'LSG', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 0.3, 58,
    { matches: 2, runs: 2, wickets: 1, batting_avg: 2.00, batting_sr: 40.00, bowling_avg: 36.00, economy: 9.50, highest_score: 2, best_bowling: '1/18', fifties: 0, hundreds: 0 },
    null),
  p('Akash Singh', 'LSG', 'Bowler', 'Indian', 'India', 'Left-hand bat', 'Left-arm fast-medium', 0.3, 58,
    { matches: 3, runs: 4, wickets: 2, batting_avg: 2.00, batting_sr: 44.44, bowling_avg: 32.50, economy: 9.30, highest_score: 3, best_bowling: '1/18', fifties: 0, hundreds: 0 },
    null),
  p('Arjun Tendulkar', 'LSG', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Left-arm fast-medium', 0.3, 55,
    { matches: 2, runs: 8, wickets: 1, batting_avg: 4.00, batting_sr: 88.89, bowling_avg: 42.00, economy: 10.50, highest_score: 6, best_bowling: '1/26', fifties: 0, hundreds: 0 },
    null),
  p('Wanindu Hasaranga', 'LSG', 'All-Rounder', 'Overseas', 'Sri Lanka', 'Right-hand bat', 'Right-arm leg-break', 1.5, 82,
    { matches: 32, runs: 180, wickets: 38, batting_avg: 11.25, batting_sr: 132.35, bowling_avg: 23.42, economy: 7.68, highest_score: 28, best_bowling: '4/20', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304640.png'),
  p('Anrich Nortje', 'LSG', 'Bowler', 'Overseas', 'South Africa', 'Right-hand bat', 'Right-arm fast', 1.5, 80,
    { matches: 42, runs: 22, wickets: 45, batting_avg: 3.14, batting_sr: 55.00, bowling_avg: 26.22, economy: 8.55, highest_score: 8, best_bowling: '4/10', fifties: 0, hundreds: 0 },
    null),
  p('Josh Inglis', 'LSG', 'Wicketkeeper', 'Overseas', 'Australia', 'Right-hand bat', 'Right-arm off-break', 1, 72,
    { matches: 12, runs: 220, wickets: 0, batting_avg: 22.00, batting_sr: 141.94, bowling_avg: 0, economy: 0, highest_score: 48, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Naman Tiwari', 'LSG', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Mukul Choudhary', 'LSG', 'Wicketkeeper', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Akshat Raghuwanshi', 'LSG', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),

  // ============================================================
  // GT - Gujarat Titans (25 players)
  // ============================================================
  p('Shubman Gill', 'GT', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 16.5, 91,
    { matches: 82, runs: 2620, wickets: 0, batting_avg: 35.41, batting_sr: 134.36, bowling_avg: 0, economy: 0, highest_score: 129, best_bowling: '0/0', fifties: 18, hundreds: 2 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316608.png'),
  p('Sai Sudharsan', 'GT', 'Batter', 'Indian', 'India', 'Left-hand bat', 'Right-arm off-break', 8.5, 80,
    { matches: 35, runs: 1020, wickets: 0, batting_avg: 32.90, batting_sr: 131.61, bowling_avg: 0, economy: 0, highest_score: 103, best_bowling: '0/0', fifties: 7, hundreds: 1 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316631.png'),
  p('Kumar Kushagra', 'GT', 'Wicketkeeper', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.65, 60,
    { matches: 4, runs: 42, wickets: 0, batting_avg: 14.00, batting_sr: 140.00, bowling_avg: 0, economy: 0, highest_score: 22, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Anuj Rawat', 'GT', 'Wicketkeeper', 'Indian', 'India', 'Left-hand bat', 'Right-arm off-break', 0.3, 62,
    { matches: 15, runs: 180, wickets: 0, batting_avg: 15.00, batting_sr: 128.57, bowling_avg: 0, economy: 0, highest_score: 42, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Jos Buttler', 'GT', 'Wicketkeeper', 'Overseas', 'England', 'Right-hand bat', 'Right-arm medium', 15.75, 86,
    { matches: 92, runs: 3050, wickets: 0, batting_avg: 36.31, batting_sr: 150.99, bowling_avg: 0, economy: 0, highest_score: 124, best_bowling: '0/0', fifties: 16, hundreds: 4 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304632.png'),
  p('Nishant Sindhu', 'GT', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 0.3, 58,
    { matches: 5, runs: 28, wickets: 2, batting_avg: 7.00, batting_sr: 112.00, bowling_avg: 38.00, economy: 8.44, highest_score: 14, best_bowling: '1/16', fifties: 0, hundreds: 0 },
    null),
  p('Washington Sundar', 'GT', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Right-arm off-break', 3.2, 76,
    { matches: 65, runs: 580, wickets: 42, batting_avg: 17.06, batting_sr: 128.89, bowling_avg: 28.33, economy: 6.95, highest_score: 46, best_bowling: '4/22', fifties: 0, hundreds: 0 },
    null),
  p('Glenn Phillips', 'GT', 'Wicketkeeper', 'Overseas', 'New Zealand', 'Right-hand bat', 'Right-arm off-break', 2, 76,
    { matches: 22, runs: 420, wickets: 5, batting_avg: 23.33, batting_sr: 155.56, bowling_avg: 34.40, economy: 8.20, highest_score: 62, best_bowling: '2/18', fifties: 2, hundreds: 0 },
    null),
  p('Mohd Arshad Khan', 'GT', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 1.3, 62,
    { matches: 6, runs: 45, wickets: 4, batting_avg: 11.25, batting_sr: 128.57, bowling_avg: 32.50, economy: 9.10, highest_score: 18, best_bowling: '2/22', fifties: 0, hundreds: 0 },
    null),
  p('Shahrukh Khan', 'GT', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 4, 72,
    { matches: 40, runs: 620, wickets: 0, batting_avg: 22.14, batting_sr: 153.47, bowling_avg: 0, economy: 0, highest_score: 68, best_bowling: '0/0', fifties: 2, hundreds: 0 },
    null),
  p('Rahul Tewatia', 'GT', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Right-arm leg-break', 4, 73,
    { matches: 95, runs: 1420, wickets: 32, batting_avg: 22.54, batting_sr: 145.10, bowling_avg: 35.69, economy: 8.65, highest_score: 73, best_bowling: '3/18', fifties: 4, hundreds: 0 },
    null),
  p('Kagiso Rabada', 'GT', 'Bowler', 'Overseas', 'South Africa', 'Left-hand bat', 'Right-arm fast', 10.75, 90,
    { matches: 68, runs: 82, wickets: 85, batting_avg: 5.47, batting_sr: 82.00, bowling_avg: 22.48, economy: 8.20, highest_score: 18, best_bowling: '4/21', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304637.png'),
  p('Mohammed Siraj', 'GT', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast', 12.25, 82,
    { matches: 82, runs: 58, wickets: 82, batting_avg: 4.83, batting_sr: 78.38, bowling_avg: 28.45, economy: 8.72, highest_score: 12, best_bowling: '4/21', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316630.png'),
  p('Prasidh Krishna', 'GT', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast', 9.5, 78,
    { matches: 40, runs: 22, wickets: 42, batting_avg: 3.67, batting_sr: 61.11, bowling_avg: 27.14, economy: 9.08, highest_score: 8, best_bowling: '4/30', fifties: 0, hundreds: 0 },
    null),
  p('Ishant Sharma', 'GT', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast', 0.75, 64,
    { matches: 92, runs: 55, wickets: 75, batting_avg: 3.67, batting_sr: 68.75, bowling_avg: 31.53, economy: 8.65, highest_score: 12, best_bowling: '3/12', fifties: 0, hundreds: 0 },
    null),
  p('Gurnoor Singh Brar', 'GT', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Left-arm fast-medium', 1.3, 64,
    { matches: 10, runs: 85, wickets: 8, batting_avg: 14.17, batting_sr: 130.77, bowling_avg: 30.00, economy: 8.80, highest_score: 28, best_bowling: '2/18', fifties: 0, hundreds: 0 },
    null),
  p('Rashid Khan', 'GT', 'Bowler', 'Overseas', 'Afghanistan', 'Right-hand bat', 'Right-arm leg-break', 18, 92,
    { matches: 118, runs: 580, wickets: 132, batting_avg: 15.26, batting_sr: 165.71, bowling_avg: 20.72, economy: 6.55, highest_score: 40, best_bowling: '5/19', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304629.png'),
  p('Manav Suthar', 'GT', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Slow left-arm orthodox', 0.3, 62,
    { matches: 4, runs: 5, wickets: 4, batting_avg: 2.50, batting_sr: 55.56, bowling_avg: 26.50, economy: 7.40, highest_score: 3, best_bowling: '2/16', fifties: 0, hundreds: 0 },
    null),
  p('Sai Kishore', 'GT', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 2, 70,
    { matches: 22, runs: 85, wickets: 18, batting_avg: 8.50, batting_sr: 106.25, bowling_avg: 28.33, economy: 7.15, highest_score: 18, best_bowling: '3/12', fifties: 0, hundreds: 0 },
    null),
  p('Jayant Yadav', 'GT', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.75, 65,
    { matches: 35, runs: 210, wickets: 22, batting_avg: 13.13, batting_sr: 110.53, bowling_avg: 32.73, economy: 7.85, highest_score: 35, best_bowling: '2/12', fifties: 0, hundreds: 0 },
    null),
  p('Ashok Sharma', 'GT', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Jason Holder', 'GT', 'All-Rounder', 'Overseas', 'West Indies', 'Right-hand bat', 'Right-arm fast-medium', 7, 78,
    { matches: 48, runs: 520, wickets: 45, batting_avg: 20.00, batting_sr: 130.00, bowling_avg: 28.89, economy: 8.62, highest_score: 52, best_bowling: '3/18', fifties: 1, hundreds: 0 },
    null),
  p('Tom Banton', 'GT', 'Wicketkeeper', 'Overseas', 'England', 'Right-hand bat', 'Right-arm off-break', 2, 68,
    { matches: 10, runs: 165, wickets: 0, batting_avg: 18.33, batting_sr: 160.19, bowling_avg: 0, economy: 0, highest_score: 42, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Prithvi Raj Yarra', 'GT', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Luke Wood', 'GT', 'Bowler', 'Overseas', 'England', 'Left-hand bat', 'Left-arm fast', 0.75, 66,
    { matches: 8, runs: 10, wickets: 8, batting_avg: 3.33, batting_sr: 66.67, bowling_avg: 28.00, economy: 8.75, highest_score: 5, best_bowling: '2/20', fifties: 0, hundreds: 0 },
    null),

  // ============================================================
  // PBKS - Punjab Kings (25 players)
  // ============================================================
  p('Shreyas Iyer', 'PBKS', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 26.75, 87,
    { matches: 125, runs: 3570, wickets: 0, batting_avg: 32.45, batting_sr: 130.66, bowling_avg: 0, economy: 0, highest_score: 101, best_bowling: '0/0', fifties: 24, hundreds: 2 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316611.png'),
  p('Prabhsimran Singh', 'PBKS', 'Wicketkeeper', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 4, 68,
    { matches: 22, runs: 420, wickets: 0, batting_avg: 21.00, batting_sr: 162.79, bowling_avg: 0, economy: 0, highest_score: 62, best_bowling: '0/0', fifties: 3, hundreds: 0 },
    null),
  p('Priyansh Arya', 'PBKS', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Right-arm medium', 3.8, 70,
    { matches: 8, runs: 145, wickets: 1, batting_avg: 20.71, batting_sr: 170.59, bowling_avg: 42.00, economy: 10.50, highest_score: 48, best_bowling: '1/22', fifties: 0, hundreds: 0 },
    null),
  p('Shashank Singh', 'PBKS', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm medium', 5.5, 74,
    { matches: 28, runs: 520, wickets: 3, batting_avg: 26.00, batting_sr: 157.58, bowling_avg: 44.00, economy: 9.80, highest_score: 68, best_bowling: '1/14', fifties: 3, hundreds: 0 },
    null),
  p('Nehal Wadhera', 'PBKS', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 4.2, 72,
    { matches: 18, runs: 340, wickets: 0, batting_avg: 22.67, batting_sr: 145.30, bowling_avg: 0, economy: 0, highest_score: 55, best_bowling: '0/0', fifties: 2, hundreds: 0 },
    null),
  p('Marcus Stoinis', 'PBKS', 'All-Rounder', 'Overseas', 'Australia', 'Right-hand bat', 'Right-arm fast-medium', 11, 82,
    { matches: 68, runs: 1480, wickets: 25, batting_avg: 27.41, batting_sr: 141.48, bowling_avg: 36.80, economy: 9.20, highest_score: 82, best_bowling: '2/14', fifties: 8, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304639.png'),
  p('Azmatullah Omarzai', 'PBKS', 'All-Rounder', 'Overseas', 'Afghanistan', 'Right-hand bat', 'Right-arm fast-medium', 2.4, 76,
    { matches: 15, runs: 260, wickets: 12, batting_avg: 20.00, batting_sr: 148.57, bowling_avg: 28.33, economy: 8.85, highest_score: 52, best_bowling: '2/18', fifties: 1, hundreds: 0 },
    null),
  p('Marco Jansen', 'PBKS', 'All-Rounder', 'Overseas', 'South Africa', 'Left-hand bat', 'Left-arm fast', 7, 82,
    { matches: 28, runs: 220, wickets: 32, batting_avg: 15.71, batting_sr: 137.50, bowling_avg: 24.69, economy: 8.40, highest_score: 38, best_bowling: '3/14', fifties: 0, hundreds: 0 },
    null),
  p('Harpreet Brar', 'PBKS', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 1.5, 68,
    { matches: 35, runs: 220, wickets: 28, batting_avg: 13.75, batting_sr: 125.71, bowling_avg: 29.64, economy: 7.65, highest_score: 35, best_bowling: '3/19', fifties: 0, hundreds: 0 },
    null),
  p('Yuzvendra Chahal', 'PBKS', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 18, 85,
    { matches: 162, runs: 72, wickets: 187, batting_avg: 3.43, batting_sr: 72.00, bowling_avg: 22.49, economy: 7.58, highest_score: 12, best_bowling: '5/14', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304628.png'),
  p('Arshdeep Singh', 'PBKS', 'Bowler', 'Indian', 'India', 'Left-hand bat', 'Left-arm fast-medium', 18, 86,
    { matches: 68, runs: 28, wickets: 82, batting_avg: 4.00, batting_sr: 73.68, bowling_avg: 23.17, economy: 8.68, highest_score: 8, best_bowling: '5/32', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316628.png'),
  p('Musheer Khan', 'PBKS', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Right-arm off-break', 0.3, 65,
    { matches: 5, runs: 68, wickets: 2, batting_avg: 17.00, batting_sr: 125.93, bowling_avg: 38.00, economy: 8.44, highest_score: 28, best_bowling: '1/14', fifties: 0, hundreds: 0 },
    null),
  p('Pyla Avinash', 'PBKS', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Harnoor Singh Pannu', 'PBKS', 'Batter', 'Indian', 'India', 'Left-hand bat', 'Right-arm off-break', 0.3, 58,
    { matches: 2, runs: 18, wickets: 0, batting_avg: 9.00, batting_sr: 112.50, bowling_avg: 0, economy: 0, highest_score: 12, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Suryansh Shedge', 'PBKS', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm medium', 0.3, 62,
    { matches: 4, runs: 42, wickets: 2, batting_avg: 14.00, batting_sr: 150.00, bowling_avg: 35.00, economy: 9.10, highest_score: 22, best_bowling: '1/16', fifties: 0, hundreds: 0 },
    null),
  p('Mitchell Owen', 'PBKS', 'All-Rounder', 'Overseas', 'Australia', 'Right-hand bat', 'Right-arm off-break', 3, 70,
    { matches: 8, runs: 165, wickets: 2, batting_avg: 23.57, batting_sr: 172.00, bowling_avg: 40.00, economy: 9.60, highest_score: 52, best_bowling: '1/18', fifties: 1, hundreds: 0 },
    null),
  p('Xavier Bartlett', 'PBKS', 'Bowler', 'Overseas', 'Australia', 'Right-hand bat', 'Right-arm fast-medium', 0.8, 70,
    { matches: 10, runs: 12, wickets: 12, batting_avg: 3.00, batting_sr: 60.00, bowling_avg: 24.17, economy: 8.28, highest_score: 5, best_bowling: '3/18', fifties: 0, hundreds: 0 },
    null),
  p('Lockie Ferguson', 'PBKS', 'Bowler', 'Overseas', 'New Zealand', 'Right-hand bat', 'Right-arm fast', 2, 82,
    { matches: 35, runs: 18, wickets: 42, batting_avg: 3.60, batting_sr: 56.25, bowling_avg: 22.62, economy: 8.12, highest_score: 6, best_bowling: '4/10', fifties: 0, hundreds: 0 },
    null),
  p('Vyshak Vijaykumar', 'PBKS', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 1.8, 68,
    { matches: 12, runs: 8, wickets: 12, batting_avg: 2.67, batting_sr: 53.33, bowling_avg: 28.83, economy: 9.15, highest_score: 4, best_bowling: '3/22', fifties: 0, hundreds: 0 },
    null),
  p('Vishnu Vinod', 'PBKS', 'Wicketkeeper', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.95, 62,
    { matches: 8, runs: 88, wickets: 0, batting_avg: 14.67, batting_sr: 146.67, bowling_avg: 0, economy: 0, highest_score: 32, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Cooper Connolly', 'PBKS', 'All-Rounder', 'Overseas', 'Australia', 'Left-hand bat', 'Slow left-arm orthodox', 0.5, 65,
    { matches: 6, runs: 68, wickets: 3, batting_avg: 13.60, batting_sr: 136.00, bowling_avg: 34.00, economy: 8.20, highest_score: 28, best_bowling: '1/14', fifties: 0, hundreds: 0 },
    null),
  p('Ben Dwarshuis', 'PBKS', 'Bowler', 'Overseas', 'Australia', 'Left-hand bat', 'Left-arm fast-medium', 0.5, 66,
    { matches: 8, runs: 12, wickets: 8, batting_avg: 3.00, batting_sr: 66.67, bowling_avg: 27.50, economy: 8.58, highest_score: 5, best_bowling: '2/18', fifties: 0, hundreds: 0 },
    null),
  p('Pravin Dubey', 'PBKS', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 0.3, 60,
    { matches: 10, runs: 15, wickets: 6, batting_avg: 5.00, batting_sr: 83.33, bowling_avg: 34.50, economy: 8.62, highest_score: 8, best_bowling: '2/22', fifties: 0, hundreds: 0 },
    null),
  p('Vishal Nishad', 'PBKS', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Yash Thakur', 'PBKS', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 1.6, 66,
    { matches: 14, runs: 12, wickets: 12, batting_avg: 3.00, batting_sr: 60.00, bowling_avg: 30.50, economy: 9.38, highest_score: 5, best_bowling: '3/28', fifties: 0, hundreds: 0 },
    null),

  // ============================================================
  // RR - Rajasthan Royals (25 players)
  // ============================================================
  p('Riyan Parag', 'RR', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 14, 82,
    { matches: 65, runs: 1380, wickets: 8, batting_avg: 28.33, batting_sr: 148.39, bowling_avg: 40.50, economy: 9.40, highest_score: 84, best_bowling: '2/18', fifties: 7, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316633.png'),
  p('Yashasvi Jaiswal', 'RR', 'Batter', 'Indian', 'India', 'Left-hand bat', 'Right-arm leg-break', 18, 92,
    { matches: 52, runs: 1820, wickets: 2, batting_avg: 38.72, batting_sr: 158.12, bowling_avg: 48.00, economy: 9.60, highest_score: 124, best_bowling: '1/18', fifties: 11, hundreds: 2 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316615.png'),
  p('Ravindra Jadeja', 'RR', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 18, 89,
    { matches: 258, runs: 3300, wickets: 170, batting_avg: 28.70, batting_sr: 135.80, bowling_avg: 29.12, economy: 7.52, highest_score: 62, best_bowling: '5/16', fifties: 4, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304625.png'),
  p('Sam Curran', 'RR', 'All-Rounder', 'Overseas', 'England', 'Left-hand bat', 'Left-arm fast-medium', 2.4, 80,
    { matches: 55, runs: 580, wickets: 48, batting_avg: 18.06, batting_sr: 138.10, bowling_avg: 30.63, economy: 8.78, highest_score: 55, best_bowling: '4/11', fifties: 1, hundreds: 0 },
    null),
  p('Donovan Ferreira', 'RR', 'Wicketkeeper', 'Overseas', 'South Africa', 'Right-hand bat', 'Right-arm off-break', 0.75, 65,
    { matches: 8, runs: 110, wickets: 0, batting_avg: 15.71, batting_sr: 145.33, bowling_avg: 0, economy: 0, highest_score: 35, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Sandeep Sharma', 'RR', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 0.75, 66,
    { matches: 104, runs: 62, wickets: 95, batting_avg: 3.65, batting_sr: 62.63, bowling_avg: 28.76, economy: 7.62, highest_score: 12, best_bowling: '4/20', fifties: 0, hundreds: 0 },
    null),
  p('Shubham Dubey', 'RR', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm medium', 0.8, 62,
    { matches: 5, runs: 62, wickets: 0, batting_avg: 15.50, batting_sr: 147.62, bowling_avg: 0, economy: 0, highest_score: 28, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Vaibhav Suryavanshi', 'RR', 'Batter', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 1.1, 68,
    { matches: 5, runs: 82, wickets: 0, batting_avg: 20.50, batting_sr: 152.83, bowling_avg: 0, economy: 0, highest_score: 36, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Lhuan-dre Pretorius', 'RR', 'Wicketkeeper', 'Overseas', 'South Africa', 'Left-hand bat', 'Right-arm off-break', 0.3, 62,
    { matches: 3, runs: 42, wickets: 0, batting_avg: 14.00, batting_sr: 168.00, bowling_avg: 0, economy: 0, highest_score: 22, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Shimron Hetmyer', 'RR', 'Batter', 'Overseas', 'West Indies', 'Left-hand bat', 'Right-arm off-break', 4.2, 78,
    { matches: 55, runs: 1080, wickets: 0, batting_avg: 28.42, batting_sr: 162.16, bowling_avg: 0, economy: 0, highest_score: 74, best_bowling: '0/0', fifties: 5, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304643.png'),
  p('Dhruv Jurel', 'RR', 'Wicketkeeper', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 14, 78,
    { matches: 18, runs: 280, wickets: 0, batting_avg: 23.33, batting_sr: 142.86, bowling_avg: 0, economy: 0, highest_score: 52, best_bowling: '0/0', fifties: 2, hundreds: 0 },
    null),
  p('Yudhvir Singh Charak', 'RR', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Right-arm medium', 0.3, 58,
    { matches: 2, runs: 12, wickets: 1, batting_avg: 6.00, batting_sr: 120.00, bowling_avg: 38.00, economy: 9.50, highest_score: 8, best_bowling: '1/22', fifties: 0, hundreds: 0 },
    null),
  p('Jofra Archer', 'RR', 'Bowler', 'Overseas', 'England', 'Right-hand bat', 'Right-arm fast', 12.5, 86,
    { matches: 42, runs: 135, wickets: 52, batting_avg: 9.00, batting_sr: 150.00, bowling_avg: 21.15, economy: 7.13, highest_score: 27, best_bowling: '3/15', fifties: 0, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304641.png'),
  p('Tushar Deshpande', 'RR', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 6.5, 74,
    { matches: 45, runs: 35, wickets: 48, batting_avg: 4.38, batting_sr: 70.00, bowling_avg: 27.83, economy: 9.48, highest_score: 12, best_bowling: '4/28', fifties: 0, hundreds: 0 },
    null),
  p('Kwena Maphaka', 'RR', 'Bowler', 'Overseas', 'South Africa', 'Left-hand bat', 'Left-arm fast', 1.5, 70,
    { matches: 5, runs: 4, wickets: 5, batting_avg: 2.00, batting_sr: 40.00, bowling_avg: 26.00, economy: 8.90, highest_score: 3, best_bowling: '2/20', fifties: 0, hundreds: 0 },
    null),
  p('Nandre Burger', 'RR', 'Bowler', 'Overseas', 'South Africa', 'Right-hand bat', 'Left-arm fast-medium', 0.5, 68,
    { matches: 8, runs: 5, wickets: 8, batting_avg: 2.50, batting_sr: 50.00, bowling_avg: 26.75, economy: 8.65, highest_score: 3, best_bowling: '2/18', fifties: 0, hundreds: 0 },
    null),
  p('Ravi Bishnoi', 'RR', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm leg-break', 7.2, 80,
    { matches: 52, runs: 22, wickets: 52, batting_avg: 3.14, batting_sr: 55.00, bowling_avg: 24.69, economy: 7.48, highest_score: 8, best_bowling: '4/16', fifties: 0, hundreds: 0 },
    null),
  p('Sushant Mishra', 'RR', 'Bowler', 'Indian', 'India', 'Left-hand bat', 'Left-arm fast-medium', 0.3, 58,
    { matches: 3, runs: 4, wickets: 2, batting_avg: 2.00, batting_sr: 44.44, bowling_avg: 34.00, economy: 9.40, highest_score: 3, best_bowling: '1/18', fifties: 0, hundreds: 0 },
    null),
  p('Yash Raj Punia', 'RR', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Vignesh Puthur', 'RR', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Brijesh Sharma', 'RR', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Slow left-arm orthodox', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Adam Milne', 'RR', 'Bowler', 'Overseas', 'New Zealand', 'Right-hand bat', 'Right-arm fast', 0.5, 70,
    { matches: 18, runs: 12, wickets: 15, batting_avg: 3.00, batting_sr: 60.00, bowling_avg: 27.60, economy: 8.80, highest_score: 5, best_bowling: '3/22', fifties: 0, hundreds: 0 },
    null),
  p('Kuldeep Sen', 'RR', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast', 0.4, 64,
    { matches: 8, runs: 8, wickets: 6, batting_avg: 2.67, batting_sr: 53.33, bowling_avg: 32.33, economy: 10.12, highest_score: 4, best_bowling: '2/22', fifties: 0, hundreds: 0 },
    null),
  p('Aman Rao Perala', 'RR', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Ravi Singh', 'RR', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),

  // ============================================================
  // SRH - Sunrisers Hyderabad (25 players)
  // ============================================================
  p('Pat Cummins', 'SRH', 'Bowler', 'Overseas', 'Australia', 'Right-hand bat', 'Right-arm fast', 18, 92,
    { matches: 50, runs: 420, wickets: 52, batting_avg: 16.15, batting_sr: 140.00, bowling_avg: 25.38, economy: 8.42, highest_score: 56, best_bowling: '4/34', fifties: 1, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316613.png'),
  p('Travis Head', 'SRH', 'Batter', 'Overseas', 'Australia', 'Left-hand bat', 'Right-arm off-break', 14, 88,
    { matches: 22, runs: 780, wickets: 2, batting_avg: 39.00, batting_sr: 176.47, bowling_avg: 42.00, economy: 9.80, highest_score: 102, best_bowling: '1/18', fifties: 4, hundreds: 1 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316616.png'),
  p('Abhishek Sharma', 'SRH', 'All-Rounder', 'Indian', 'India', 'Left-hand bat', 'Slow left-arm orthodox', 14, 82,
    { matches: 55, runs: 1280, wickets: 18, batting_avg: 27.23, batting_sr: 162.44, bowling_avg: 34.78, economy: 8.20, highest_score: 85, best_bowling: '2/14', fifties: 6, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316627.png'),
  p('Heinrich Klaasen', 'SRH', 'Wicketkeeper', 'Overseas', 'South Africa', 'Right-hand bat', 'Right-arm off-break', 23, 90,
    { matches: 38, runs: 1320, wickets: 0, batting_avg: 40.00, batting_sr: 175.17, bowling_avg: 0, economy: 0, highest_score: 104, best_bowling: '0/0', fifties: 8, hundreds: 1 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316617.png'),
  p('Nitish Kumar Reddy', 'SRH', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm medium', 6, 76,
    { matches: 22, runs: 380, wickets: 8, batting_avg: 23.75, batting_sr: 142.86, bowling_avg: 34.00, economy: 9.10, highest_score: 54, best_bowling: '2/18', fifties: 2, hundreds: 0 },
    null),
  p('Ishan Kishan', 'SRH', 'Wicketkeeper', 'Indian', 'India', 'Left-hand bat', 'Right-arm off-break', 11.25, 80,
    { matches: 105, runs: 2782, wickets: 0, batting_avg: 28.39, batting_sr: 136.49, bowling_avg: 0, economy: 0, highest_score: 99, best_bowling: '0/0', fifties: 17, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/316600/316620.png'),
  p('Aniket Verma', 'SRH', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Smaran Ravichandran', 'SRH', 'Batter', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Harsh Dubey', 'SRH', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Kamindu Mendis', 'SRH', 'All-Rounder', 'Overseas', 'Sri Lanka', 'Left-hand bat', 'Right-arm off-break', 1.2, 75,
    { matches: 10, runs: 180, wickets: 5, batting_avg: 22.50, batting_sr: 138.46, bowling_avg: 32.00, economy: 7.80, highest_score: 42, best_bowling: '2/18', fifties: 0, hundreds: 0 },
    null),
  p('Harshal Patel', 'SRH', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 8, 78,
    { matches: 108, runs: 420, wickets: 118, batting_avg: 11.33, batting_sr: 120.00, bowling_avg: 24.24, economy: 8.65, highest_score: 34, best_bowling: '5/27', fifties: 0, hundreds: 0 },
    null),
  p('Brydon Carse', 'SRH', 'All-Rounder', 'Overseas', 'England', 'Right-hand bat', 'Right-arm fast', 3.8, 76,
    { matches: 12, runs: 85, wickets: 14, batting_avg: 12.14, batting_sr: 128.79, bowling_avg: 26.43, economy: 8.55, highest_score: 22, best_bowling: '3/22', fifties: 0, hundreds: 0 },
    null),
  p('Jaydev Unadkat', 'SRH', 'Bowler', 'Indian', 'India', 'Left-hand bat', 'Left-arm fast-medium', 1, 68,
    { matches: 95, runs: 155, wickets: 85, batting_avg: 5.74, batting_sr: 86.11, bowling_avg: 28.82, economy: 8.28, highest_score: 18, best_bowling: '5/25', fifties: 0, hundreds: 0 },
    null),
  p('Eshan Malinga', 'SRH', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast', 1.2, 62,
    { matches: 5, runs: 4, wickets: 4, batting_avg: 2.00, batting_sr: 50.00, bowling_avg: 30.50, economy: 9.20, highest_score: 3, best_bowling: '2/22', fifties: 0, hundreds: 0 },
    null),
  p('Zeeshan Ansari', 'SRH', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Slow left-arm orthodox', 0.3, 58,
    { matches: 3, runs: 5, wickets: 2, batting_avg: 2.50, batting_sr: 55.56, bowling_avg: 32.00, economy: 7.80, highest_score: 3, best_bowling: '1/14', fifties: 0, hundreds: 0 },
    null),
  p('Shivang Kumar', 'SRH', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm medium', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Salil Arora', 'SRH', 'Wicketkeeper', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Sakib Hussain', 'SRH', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Left-arm fast-medium', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Onkar Tarmale', 'SRH', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Amit Kumar', 'SRH', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Praful Hinge', 'SRH', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast-medium', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Krains Fuletra', 'SRH', 'All-Rounder', 'Indian', 'India', 'Right-hand bat', 'Right-arm off-break', 0.3, 55,
    { matches: 0, runs: 0, wickets: 0, batting_avg: 0, batting_sr: 0, bowling_avg: 0, economy: 0, highest_score: 0, best_bowling: '0/0', fifties: 0, hundreds: 0 },
    null),
  p('Liam Livingstone', 'SRH', 'All-Rounder', 'Overseas', 'England', 'Right-hand bat', 'Right-arm leg-break', 13, 83,
    { matches: 38, runs: 720, wickets: 15, batting_avg: 24.83, batting_sr: 158.59, bowling_avg: 32.00, economy: 8.72, highest_score: 72, best_bowling: '2/18', fifties: 4, hundreds: 0 },
    'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/304600/304644.png'),
  p('Shivam Mavi', 'SRH', 'Bowler', 'Indian', 'India', 'Right-hand bat', 'Right-arm fast', 0.75, 66,
    { matches: 30, runs: 22, wickets: 25, batting_avg: 3.67, batting_sr: 61.11, bowling_avg: 30.80, economy: 9.42, highest_score: 8, best_bowling: '3/20', fifties: 0, hundreds: 0 },
    null),
  p('Jack Edwards', 'SRH', 'All-Rounder', 'Overseas', 'Australia', 'Right-hand bat', 'Right-arm off-break', 0.5, 62,
    { matches: 5, runs: 55, wickets: 3, batting_avg: 11.00, batting_sr: 130.95, bowling_avg: 36.00, economy: 8.80, highest_score: 22, best_bowling: '1/16', fifties: 0, hundreds: 0 },
    null),
];

async function seedPlayers() {
  console.log(`\n=== IPL 2026 Player Seed Script ===`);
  console.log(`Total players to upsert: ${players.length}`);
  console.log(`Supabase URL: ${supabaseUrl}\n`);

  const teamCounts: Record<string, number> = {};
  for (const pl of players) {
    teamCounts[pl.team] = (teamCounts[pl.team] || 0) + 1;
  }
  console.log('Players per team:');
  for (const [team, count] of Object.entries(teamCounts)) {
    console.log(`  ${team}: ${count}`);
  }
  console.log('');

  const BATCH_SIZE = 25;
  let inserted = 0;
  let errors = 0;

  for (let i = 0; i < players.length; i += BATCH_SIZE) {
    const batch = players.slice(i, i + BATCH_SIZE);
    const batchNum = Math.floor(i / BATCH_SIZE) + 1;
    const totalBatches = Math.ceil(players.length / BATCH_SIZE);

    process.stdout.write(`Upserting batch ${batchNum}/${totalBatches} (${batch.length} players)... `);

    const { error } = await supabase
      .from('players')
      .upsert(batch, { onConflict: 'name,team,season', ignoreDuplicates: false });

    if (error) {
      console.error(`FAILED`);
      console.error(`  Error: ${error.message}`);
      errors += batch.length;
    } else {
      console.log(`OK`);
      inserted += batch.length;
    }
  }

  console.log(`\n=== Seed Complete ===`);
  console.log(`  Upserted: ${inserted}`);
  console.log(`  Errors:   ${errors}`);
  console.log(`  Total:    ${players.length}`);

  if (errors > 0) {
    process.exit(1);
  }
}

seedPlayers().catch((err) => {
  console.error('Unexpected error:', err);
  process.exit(1);
});
